# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XbetaZb_cpp <- function(X, beta, Z, b) {
    .Call('JMbayesCpp_XbetaZb_cpp', PACKAGE = 'JMbayesCpp', X, beta, Z, b)
}

Xbeta_cpp <- function(X, beta) {
    .Call('JMbayesCpp_Xbeta_cpp', PACKAGE = 'JMbayesCpp', X, beta)
}

dnorm_cpp <- function(y, X, beta, Z, b, sigma) {
    .Call('JMbayesCpp_dnorm_cpp', PACKAGE = 'JMbayesCpp', y, X, beta, Z, b, sigma)
}

dmvnorm_cpp <- function(x, mean, sigma, logd = FALSE) {
    .Call('JMbayesCpp_dmvnorm_cpp', PACKAGE = 'JMbayesCpp', x, mean, sigma, logd)
}

logSurvival_cpp <- function(Xs, betas_new, Zs, b, alphas_new, W_time_independent, gammas_new, W2s, Bs_gammas_new, wk, P) {
    .Call('JMbayesCpp_logSurvival_cpp', PACKAGE = 'JMbayesCpp', Xs, betas_new, Zs, b, alphas_new, W_time_independent, gammas_new, W2s, Bs_gammas_new, wk, P)
}

